name: fix_json
modelConf:
  - name: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  - ctx: 4096
inferParams:
  - top_p: 0.35
  - temperature: 0.0
template: |-
  <s>[INST] fix this invalid json:

  ```json
  {"a":2, b: some text,} // a comment
  ``` [/INST]
  ```json
  {"a":2, "b": "some text"}
  ``` </s> [INST] fix this invalid json:

  ```json
  {prompt}
  ``` [/INST]