// Copyright 2025 The contributors of Goinfer.
// This file is part of Goinfer, a LLM proxy under the MIT License.
// SPDX-License-Identifier: MIT

// Package conf reads/writes configuration
package conf

import (
	"bytes"
	"strings"
)

// LlamaINI is the llama.cpp config filename.
const LlamaINI = "llama.ini"

// WriteLlamaINI generates the llama.cpp configuration.
func WriteLlamaINI(yml []byte) error {
	header := `# DO NOT EDIT - This file is generated by Goinfer.
#
# llama.cpp configurations using Model Presets:
#
#     llama-server --models-preset ./llama.ini
#
# Each section in this file defines a new preset.
# Keys within a section correspond to command-line arguments (without leading dashes).
# For example, the argument --n-gpu-layer 123 is written as n-gpu-layer = 123.
# Short argument forms (e.g., c, ngl) and environment variable names (e.g., LLAMA_ARG_N_GPU_LAYERS) are also supported as keys.
#
# Doc: https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md#model-presets

version = 1
`
	return writeWithHeader(LlamaINI, header, yml)
}

// GenSwapYAMLData generates the llama-swap configuration.
func (cfg *Cfg) GenLlamaINI() []byte {
	var out bytes.Buffer

	// For each model, set two model settings:
	// 1. for the OpenAI endpoints
	// 2. for the /completion endpoint (prefix with A_ and hide the model)
	for model, mi := range cfg.getInfo() {
		out.Write(genModel(model, mi.Path, mi.Flags))
		out.Write(genModel(model+":A", mi.Path, cfg.Llama.Goinfer+" "+mi.Flags))
	}

	return out.Bytes()
}

// Add the model settings within the llama-swap configuration.
func genModel(name, path, flags string) []byte {
	out := bytes.NewBufferString(`
[` + name + `]
model = ` + path)

	boolean := false

	for arg := range strings.FieldsSeq(flags) {
		if arg[0] == '-' {
			if boolean {
				out.WriteString(" true")
			}
			boolean = true
			out.WriteByte('\n')
			if len(arg) == 2 {
				out.WriteByte(arg[1])
			} else {
				i := 1
				if arg[1] == '-' {
					i = 2
				}
				out.WriteString(arg[i:])
			}
			out.WriteByte(' ')
			out.WriteByte('=')
			continue
		}
		boolean = false
		out.WriteByte(' ')
		out.WriteString(arg)
	}

	if boolean {
		out.WriteString(" true\n")
	} else {
		out.WriteByte('\n')
	}

	return out.Bytes()
}
